extends: default

ignore:
  - .venv
  - themes

rules:
  document-start: disable  # personal
  line-length:
    max: 150
  new-lines: disable  # mix of win and unix endlines
  truthy:
    check-keys: false  # to allow Github 'on:' syntax
